### ISSUE TITLE
Match UI print should state exactly which row/col/diag match has been hit

### ISSUE THREAD

**Issue by samus9001** [samus9001/Slot-Machine-Game-Exercise#19]
When there is a matching row/col/diag, the UI method display that prints this should state exactly which one this is as opposed to it currently not specifying any.

**Comment by incredibleLeitman** [comment]
If you want to display the exact line which was hit and not just the amount, you need more than just an integer that counts the lines. One approach for this would be to use a list of int for example and instead of just increasing the value in your CheckWinningX methods add the current line to the list

I also think instead of using "i" in every for loop you should come up with a specific name which makes your code instantly more readable.

```for (int i = 0; i < amountRows; i++)```
---> 
```for (int row = 0; row < amountRows; row++)```
